Item:
  DisplayName: "Waystone"
  Lore: []
  LoreWithName:
    - "<white>Name: <aqua>{name}"
  Material: LODESTONE
  EnchantmentGlint: true
  Rarity: UNCOMMON
  Recipe:
    Layout:
      - SES
      - RLR
      - STS
    Ingredients:
      S: CHISELED_STONE_BRICKS
      E: ENDER_PEARL
      L: LODESTONE
      R: REDSTONE
      T: TARGET
DefaultWaystone:
  Name: "Waystone #{id}"
  GloballyAccessible: true
Functions:
  RenameByNameTag:
    Enabled: true
    UseDialog: false
  AddFriends:
    Enabled: true
    SpecialBlockMaterial: TARGET
Sounds:
  Activation:
    Enabled: true
    Key: "block.beacon.activate"
    Volume: 1
    Pitch: 1.5
  Deactivation:
    Enabled: true
    Key: "block.beacon.deactivate"
    Volume: 1
    Pitch: 1.5
  Disallowed:
    Enabled: true
    Key: "entity.villager.no"
    Volume: 0.5
    Pitch: 1
  Teleported:
    Enabled: true
    Key: "entity.player.teleport"
    Volume: 0.5
    Pitch: 1
Messages:
  NameInputDialog:
    Title: "Waystones"
    Notice: "Your waystone will be open to public, unless visibility is changed using <blue>echo shard"
    InputLabel: "Enter waystone name:"
  WaystonesListDialog:
    Title: "Current waystone - <bold>{current_name}"
    WaystoneButton: "{name} ({attributes})"
    WaystoneTooltip:
      - "Location: <aqua>{x}, {y}, {z}"
      - "World: {world}"
      - "Owner: {owner}"
  WaystoneDestroyedNoticeDialog:
    Title: "Something happened"
    Message: "<red>Waystone <white>{name}</white> doesn't exist anymore! This can happen when your waystone block gets destroyed by an explosion or something else.</red>"
    Checkbox: "Remove this waystone from the list (<red>irreversible</red>)"
    BackToList: "Back to the list"
  WorldReplacedNames:
    world: "<green>Overworld</green>"
    world_nether: "<red>Nether</red>"
    world_the_end: "<yellow>The End</yellow>"
  WaystoneAttributes:
    Separator: ", "
    Public: "<green>public</green>"
    Private: "<red>private</red>"
    Destroyed: "<red>destroyed</red>"
    LastlyUsed: "<yellow>recent</yellow>"
  ArrowUp: "↑"
  ArrowDown: "↓"
  Close: "Close"
  Done: "Done"